- name: Pull docker image async
  shell: docker pull "{{iota_core_docker_image_repo}}:{{iota_core_docker_image_tag}}"
  async: 300
  poll: 5

- name: Create node directory
  file:
    path: /opt/iota-core
    state: directory
    mode: '0755'

- name: Download snapshot file
  get_url:
    url: "{{ customSnapshotUrl if customSnapshotUrl else defaultSnapshotUrl }}"
    dest: /opt/iota-core/snapshot.bin
    mode: '0644'

- name: Copy configuration file
  copy:
    src: config.json
    dest: /opt/iota-core/config.json
    mode: '0644'

- name: Template docker-compose.yml
  template:
    src: docker-compose-iota-core.yml.j2
    dest: /opt/iota-core/docker-compose.yml
    mode: '0644'

- name: Kill existing services
  community.docker.docker_compose:
    project_src: /opt/iota-core
    timeout: 1
    state: present
    stopped: yes

- name: Tear down existing services
  community.docker.docker_compose:
    project_src: /opt/iota-core
    state: absent

- name: Create DB directory
  file:
    path: /opt/iota-core/data
    state: directory
    mode: '0777'

- name: Remove DB
  shell:
    cmd: rm -rf /opt/iota-core/data/*

- name: Clean conntrack
  shell:
    cmd: conntrack -D -p udp
  ignore_errors: true # sometimes conntrack might not be installed

- name: Run node
  community.docker.docker_compose:
    project_src: /opt/iota-core
    timeout: 180
    state: present
    pull: yes
