metrics:
  hosts:
    metrics-01.feature.shimmer.iota.cafe:

cores:
  children:
    internal_nodes:
      hosts:
        node-01.feature.shimmer.iota.cafe:
          validatorAccountAddress: "{{ NODE_01_VALIDATOR_ACCOUNTADDRESS }}"
          validatorPrvKey: "{{ NODE_01_VALIDATOR_PRIVKEY }}"
          p2pIdentityPrvKey: "{{ NODE_01_P2PIDENTITY_PRIVKEY }}"
        node-02.feature.shimmer.iota.cafe:
          validatorAccountAddress: "{{ NODE_02_VALIDATOR_ACCOUNTADDRESS }}"
          validatorPrvKey: "{{ NODE_02_VALIDATOR_PRIVKEY }}"
          p2pIdentityPrvKey: "{{ NODE_02_P2PIDENTITY_PRIVKEY }}"
        node-03.feature.shimmer.iota.cafe:
          validatorAccountAddress: "{{ NODE_03_VALIDATOR_ACCOUNTADDRESS }}"
          validatorPrvKey: "{{ NODE_03_VALIDATOR_PRIVKEY }}"
          p2pIdentityPrvKey: "{{ NODE_03_P2PIDENTITY_PRIVKEY }}"
        node-04.feature.shimmer.iota.cafe:
          p2pIdentityPrvKey: "{{ NODE_04_P2PIDENTITY_PRIVKEY }}"
        node-05.feature.shimmer.iota.cafe:
          p2pIdentityPrvKey: "{{ NODE_05_P2PIDENTITY_PRIVKEY }}"
  vars:
