name: Build Docker

on:
  pull_request:
    paths:
      - "Dockerfile"
  push:
    branches:
      - develop

jobs:
  build:
    name: Build Docker
    runs-on: self-hosted
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Build Docker image
        run: DOCKER_BUILDKIT=1 docker build . --file Dockerfile --tag iota-core:latest

      - name: Test Docker image
        run: docker run --rm --name iota-core iota-core:latest --version 2>/dev/null | grep -q "iota-core"
