name: GolangCIlint

on:
  pull_request:
    paths-ignore:
      - 'documentation/**'
      - 'scripts/**'
      - 'tools/**'

jobs:
  golangci-lint:
    name: GolangCI-Lint
    runs-on: self-hosted
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      #- name: Checkout custom linter
      #  uses: actions/checkout@v4
      #  with:
      #    repository: iotaledger/typegroupingcheck
      #    path: typegroupingcheck

      #- name: Setup go
      #  uses: actions/setup-go@v5
      #  with:
      #    go-version-file: './typegroupingcheck/go.mod'

      #- name: Build custom linter
      #  working-directory: ./typegroupingcheck
      #  run: |
      #    go build -buildmode=plugin -o typegroupingcheck.so

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          skip-cache: true
          version: latest
          install-mode: goinstall
          args: --timeout=10m # --enable typegroupingcheck
